apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Chart.name }}
  name: {{ .Chart.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Chart.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Chart.name}}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: hello
        ports:
            - containerPort: 80
        env:
            - name: NGINX_HELLO_MESSAGE
              value: "{{ .Values.customMessage }}"
        resources: {}
status: {}