replicaCount: 1

image:
  repository: nginxdemos/hello
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: NodePort
  port: 80
  nodePort: 30007  # Optional, for testing in Minikube

customMessage: "Sample Webapp Created via Helm"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
